<head>
    <link rel="stylesheet" href="style.css" type="text/css">
</head>

<footer>
<div id="column">  
    <h2>Dapatkan Bantuan dan Dukungan</h2>      
    Untuk mendapatkan petunjuk atau dukungan dari kami, kunjungi situs 
    <a href="http://support.directnews.com">support.directnews.com</a> 
    dan submit form anda. 
</div> 
<div id="column">  
    <h2>Hubungi Kami</h2>  
    Jl. Parikesit 75<br>  
    Surabaya 66666 Jawa Timur<br>  
    (+6231) 5556667 </div> <div id="column">  
        <h2>Temukan Kami di...</h2>  
            <a href="http://facebook.com/directnewsaccess">Facebook</a><br>  
            <a href="http://twitter.com/directnewsaccess">Twitter</a>
</div> 
</footer>