<head>
    <link rel="stylesheet" href="style.css" type="text/css">
</head>

<div id="content">
    <div id="single">
        <div id="featured-image"
style="background: url(images/1.jpg)">&nbsp;</div>
        <h2> Penemuan Telegram Kabarkan Dahsyatnya Letusan Krakatau</h2>
        <div align = "justify">KOMPAS.com - Dibandingkan letusan Gunung Tambora di Sumbawa (Nusa Tenggara Timur) 
        pada 1815, letusan Gunung Krakatau masih kalah besar, baik kekuatan maupun dampaknya. Berbeda dengan letusan 
        Tambora yang terekam samar dan dampak globalnya baru dideteksi lebih dari 100 tahun kemudian, letusan Krakatau 
        diketahui warga dunia dalam bilangan jam [...]</div>
            <div id="more"><a href="article-1.html">Baca Selengkapnya</a></div>
    </div>
    <div id="single">
        <div id="featured-image"
style="background: url(images/2.jpg)">&nbsp;</div>
        <h2>Pesawat Tanpa Awak UGM Berdaya Jelajah 200 Kilometer</h2>      
        <div align = "justify">JAKARTA, KOMPAS.com - Untuk memantau batas wilayah atau situasi dan kondisi lokasi 
        bencana alam dengan biaya murah dan efektif, dibutuhkan teknologi pesawat tanpa awak. 
        Universitas Gadjah Mada (UGM) turut memamerkan hasil risetnya, berupa pesawat udara 
        tanpa awak mini (Mini UAV) pada Forum Riset Industri Indonesia ke-3 2011, Rabu (30/11/2011) 
        di [...] </div>
            <div id="more"><a href="article-2.html">Baca Selengkapnya</a></div>
    </div>
    <div id="single">
        <div id="featured-image"
style="background: url(images/3.jpg)">&nbsp;</div>
        <h2>Prasasti Maya Bukan Petunjuk Kiamat</h2>
        <div align = "justify"> KOMPAS.com — Beberapa waktu lalu, National Institute of Anthropology and History di Meksiko 
        mengumumkan penemuan Prasasti Comalcalco. Prasasti itu memiliki kalender lingkaran, kombinasi 
        posisi hari dan bulan yang berulang tiap 52 tahun. Tanggal yang tertera pada prasasti, diduga 
        21 Desember 2012, terkait dengan akhir Baktun (periode tiap 394 tahun) ke-13. Angka 13 [...]</div>
            <div id="more"><a href="article-3.html">Baca Selengkapnya</a></div> 
</div>
<div id="single">
    <div id="featured-image"
style="background: url(images/4.jpg)">&nbsp;</div>
    <h2>Seperlima Gletser Himalaya Mencair</h2>
    <div align = "justify">KOMPAS.com — Sebanyak seperlima gletser di Himalaya telah menyusut karena mencair dalam kurun 30 tahun 
    terakhir. Rinciannya antara lain, 21 persen gletser di Nepal dan 22 persen gletser di Butan mencair. 
    Fakta itu merupakan hasil penelitian International Center for Integrated Mountain Development (Icimod), 
    sebuah organisasi yang berbasis di Kathmandu, Nepal [...] </div>
        <div id="more"><a href="article-4.html">Baca Selengkapnya</a></div> 
</div>
<div id="single">
    <div id="featured-image"
style="background: url(images/5.jpg)">&nbsp;</div>
    <h2>Asteroid Vesta dalam Video 3D</h2>
    <div align = "justify"> PASADENA, KOMPAS.com - Asteroid Vesta adalah salah satu asteroid terbesar di Tata Surya. Diameter 
    asteroid ini mencapai 530 km. Asteroid ini ditemukan oleh Heinrich Wilhelm Olbers pada 29 Maret 1807. 
    Penasaran seperti apa rupa asteroid Vesta? NASA telah memproduksi citra yang menyuguhkan rupa asteroid 
    Vesta dalam versi 3D. Citra tersebut diambil oleh wahana antariksa [...] </div>  
        <div id="more"><a href="article-5.html">Baca Selengkapnya</a></div> 
    </div>
</div>