<head>
    <link rel="stylesheet" href="style.css" type="text/css">
</head>

<nav>                   
    <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="#">Artikel</a>
                <ul class="submenu">
                        <li><a href="#">Sains</a></li>
                        <li><a href="#">Bola</a></li>
                </ul>
            </li>
            <li><a href="http://www.youtube.com">Video</a></li>
            <li><a href="kontak.html">Kontak</a></li>
            <li><a href="#">Sitemap</a></li>
     </ul>
</nav>